# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.EmailField(max_length=150)),
                ('title', models.CharField(max_length=50)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Profile')),
            ],
        ),
    ]
