# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_friendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='nuzzzzzzzzzzzzzzzzzzzzzzz', max_length=105),
            preserve_default=False,
        ),
    ]
