# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmessage',
            name='from_user',
            field=models.CharField(max_length=105),
        ),
    ]
