# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
