# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20160825_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 25, 18, 59, 37, 704462)),
            preserve_default=False,
        ),
    ]
