# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_profile_firends2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, default='Post', max_length=25, null=True),
        ),
    ]
