# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 00:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20161107_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='amount_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='likes',
            field=models.CharField(default='', max_length=100000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
