# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20161211_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='users',
        ),
    ]
