# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20161212_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='private_message',
            field=models.ManyToManyField(related_name='messages', to='chat.Profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='share',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('Only Me', 'Only Me')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, default='Post', max_length=400, null=True),
        ),
    ]
