# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 03:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20170104_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='private_message',
        ),
        migrations.AddField(
            model_name='chat',
            name='private_message',
            field=models.CharField(default='', max_length=100000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='chat',
            name='share',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('Only Me', 'Only Me'), ('Private Message', 'Private Message')], max_length=50),
        ),
    ]
