# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20170104_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
