# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_friendmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmessage',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
