# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_auto_20170117_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firends2',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Decline to identify', 'Decline to identify')], max_length=30),
        ),
    ]
